[package]
name = "flexi_func_declarative"
description = "This crate exposes the fb! macro to create a function with a flexible signature."
license = "MIT"
version = "0.2.7"
edition = "2021"
readme = "README.md"
categories = ["rust-patterns", "parsing", "asynchronous"]

[dependencies]
