[package]
name = "flexi_func_declarative"
description = "This crate exposes the fb! macro to create a function with a flexible signature."
license = "MIT"
version = "0.2.4"
edition = "2021"

[dependencies]
